name: Build firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - nice_nano_v2
        shield:
          - left
          - right
          - settings_reset
          - ''

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install West
        run: pip install --upgrade west

      - name: Initialize West
        run: west init -l app

      - name: Update West
        run: west update

      - name: Export Zephyr
        run: west zephyr-export

      - name: Install Dependencies
        run: |
          pip install -r zephyr/scripts/requirements.txt
          pip install -r bootloader/requirements.txt

      - name: Prepare variables
        id: variables
        run: |
          SUFFIX=$(uuidgen | cut -c1-8)
          if [ -n "${{ matrix.shield }}" ]; then
            EXTRA_CMAKE_ARGS="-DSHIELD=${{ matrix.shield }}"
            ARTIFACT_NAME="${{ matrix.shield }}-${{ matrix.board }}-zmk-${SUFFIX}"
            DISPLAY_NAME="${{ matrix.shield }} - ${{ matrix.board }}"
          else
            EXTRA_CMAKE_ARGS=
            DISPLAY_NAME="${{ matrix.board }}"
            ARTIFACT_NAME="${{ matrix.board }}-zmk-${SUFFIX}"
          fi
          echo "extra-cmake-args=${EXTRA_CMAKE_ARGS}" >> $GITHUB_OUTPUT
          echo "artifact-name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
          echo "display-name=${DISPLAY_NAME}" >> $GITHUB_OUTPUT

      - name: Build (${{ steps.variables.outputs.display-name }})
        run: |
          west build -s app -b ${{ matrix.board }} -- -DZMK_CONFIG=$(realpath config) ${{ steps.variables.outputs.extra-cmake-args }}
          mkdir -p build/artifacts
          cp build/zephyr/zmk.uf2 build/artifacts/${{ steps.variables.outputs.artifact-name }}.uf2 || true
          cp build/zephyr/zmk.hex build/artifacts/${{ steps.variables.outputs.artifact-name }}.hex || true

      - name: Archive (${{ steps.variables.outputs.display-name }})
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.variables.outputs.artifact-name }}
          path: build/artifacts
